#MakeFile for Project 1A
#Siddharth Joshi - 105032378

.SILENT:


default: lab1a.c
	gcc std=c99 -Wall -Wextra -g -o lab1a lab1a.c
clean:
	rm -f lab1a *.tar* *~

dist:
	tar -czf lab1a-105032378.tar.gz lab1a.c README Makefile 
