.SILENT:

dist: git.png connected.png build_run.png copy.png my_beaglebone.jpg README Makefile
	tar -czf lab4a-105032378.tar.gz git.png connected.png build_run.png copy.png my_beaglebone.jpg README Makefile